# items.py
def get_test_data():
    items = [
        {"id": 1, "width": 5, "height": 7},
        {"id": 2, "width": 3, "height": 8},
        {"id": 3, "width": 6, "height": 4},
        {"id": 4, "width": 4, "height": 6},
        {"id": 5, "width": 7, "height": 3},
        {"id": 6, "width": 2, "height": 9},
        {"id": 7, "width": 8, "height": 5},
        {"id": 8, "width": 4, "height": 4},
        {"id": 9, "width": 6, "height": 6},
        {"id": 10, "width": 3, "height": 3},
        {"id": 11, "width": 5, "height": 5},
        {"id": 12, "width": 7, "height": 4},
        {"id": 13, "width": 4, "height": 8},
        {"id": 14, "width": 6, "height": 3},
        {"id": 15, "width": 3, "height": 7},
        {"id": 16, "width": 5, "height": 4},
        {"id": 17, "width": 8, "height": 3},
        {"id": 18, "width": 4, "height": 5},
        {"id": 19, "width": 7, "height": 6},
        {"id": 20, "width": 3, "height": 4},
        {"id": 21, "width": 6, "height": 5},
        {"id": 22, "width": 5, "height": 3},
        {"id": 23, "width": 4, "height": 7},
        {"id": 24, "width": 8, "height": 4},
        {"id": 25, "width": 3, "height": 6},
        {"id": 26, "width": 7, "height": 5},
        {"id": 27, "width": 5, "height": 8},
        {"id": 28, "width": 4, "height": 3},
        {"id": 29, "width": 6, "height": 7},
        {"id": 30, "width": 8, "height": 6},
    ]
    return items